Repository 5-1-Mogazoa/Mogazoa, pull requests merged in 2024-04, with the labels that each got.

#210 Chore: 상품 편집 요청 실패시 "이미 등록된 상품명이에요" 모달팝업 보여주기
  src/components/common/modal/Modal.tsx
  src/components/product/ModalEdit/index.tsx
  src/constant/MODAL_BUTTON.ts
Labels: 기능

#212 Fix : localStorage is not defined 에러 해결
  pages/products/[productId]/index.tsx
  src/components/product/ReviewItem/index.tsx
Labels: 버그

#217 Fix: 리뷰 생성, 편집 모달 안 닫히는 오류 수정
  src/components/product/ModalEditReview/index.tsx
  src/components/product/ModalReview/index.tsx
Labels: 버그

#219 Feat/218/compare버튼스타일수정
  src/components/compare/Compare.tsx
  src/components/compare/Product1.tsx
  src/components/compare/Product2.tsx
Labels: 디자인

#221 Design: 버튼 수정
  src/components/common/button/Styled/StyledButton.tsx
  src/components/compare/Styled/BodyContainer.tsx
Labels: 디자인

#215 fix: 유저 데이터 수정 시, 바로 적용
  src/components/profiles/MyPageProfileButtons.tsx
  src/components/profiles/ProfileEditModal.tsx
  src/components/profiles/UserProfile.tsx
Labels: 버그

#226 Design: 공통 버튼 tablet width 수정
  src/components/common/button/Styled/StyledButton.tsx
Labels: 디자인

#229 Feat: 상품결과 디자인수정
  src/components/common/chip/Styled/StyledCompareChip.tsx
  src/components/compare/Compare.tsx
  src/components/compare/Description.tsx
  src/components/compare/Styled/StyledTable.tsx
Labels: 디자인
