Repository 5-1-Mogazoa/Mogazoa, pull requests merged in 2024-03, with the labels that each got.

#9 Design/8/전체배경및아이콘
  public/icons/LoadingLarge.svg
  public/icons/LoadingSmall.svg
  public/icons/LogoLarge.svg
  public/icons/LogoSmall.svg
  public/icons/add.svg
  public/icons/category.svg
  public/icons/close.svg
  public/icons/dropdown.svg
  public/icons/dropup.svg
  public/icons/google.svg
  public/icons/hambugermenu.svg
  public/icons/heartempty.svg
  public/icons/heartfull.svg
  public/icons/kakao.svg
  public/icons/messagebubble.svg
  public/icons/myprofile.svg
  public/icons/photo.svg
  public/icons/search.svg
  public/icons/share.svg
  public/icons/star.svg
  public/icons/upempty.svg
  public/icons/upfull.svg
  public/icons/visibilityOff.svg
  public/icons/visibilityOn.svg
  styles/GlobalStyle.ts
Labels: 디자인

#13 design: 전체 배경 재설정
  styles/GlobalStyle.ts
Labels: 디자인

#11 Design/5/input컴포넌트디자인
  src/components/common/input/11
  src/components/common/input/ImageInput.tsx
  src/components/common/input/NicknameInput.tsx
  src/components/common/input/ProductNameInput.tsx
  src/components/common/input/Styled/StyledImageInput.tsx
  src/components/common/input/Styled/StyledNicknameInput.tsx
  src/components/common/input/Styled/StyledProductnameInput.tsx
  src/components/common/input/Styled/StyledTextBox.tsx
  src/components/common/input/TextBox.tsx
Labels: 디자인

#15 Design/14/chip컴포넌트디자인구현
  src/components/common/chip/11
  src/components/common/chip/CompareChip.tsx
  src/components/common/chip/Styled/StyledCategoryChip.tsx
  src/components/common/chip/Styled/StyledCompareChip.tsx
  src/components/common/chip/Styled/StyledRankingChip.tsx
  src/components/common/chip/Styled/StyledThumbs.tsx
  src/components/common/chip/Thumbs.tsx
Labels: 디자인

#23 Design/16/button디자인구현
  public/icons/addButton.svg
  src/components/common/button/11
  src/components/common/button/DropDown.tsx
  src/components/common/button/SortDropdown.tsx
  src/components/common/button/Styled/StyledButton.tsx
  src/components/common/button/Styled/StyledDropDownMenu.tsx
  src/components/common/button/Styled/StyledProductAddButton.tsx
  src/components/common/button/Styled/StyledSortDropdown.tsx
Labels: 디자인

#25 refactor: ranking chip 3위 이하 타입 통합
  src/components/common/chip/Styled/StyledRankingChip.tsx
Labels: 디자인

#29 Design/26/menu디자인
  src/components/common/input/Styled/StyledImageInput.tsx
  src/components/common/menu/11
  src/components/common/menu/CategoryMenuBar.tsx
  src/components/common/menu/RankingListItem.tsx
  src/components/common/menu/Styled/StyledCategoryMenuBar.tsx
  src/components/common/menu/Styled/StyledRankingListItem.tsx
Labels: 디자인

#27 Feat : card 컴포넌트 구현
  src/components/common/card/11
  src/components/common/card/Card.tsx
  src/components/common/card/Styled/StyledCard.tsx
Labels: 기능, 디자인

#32 Feat: products페이지/ProductDetail 컴포넌트 디자인 구현
  next.config.mjs
  pages/products/[productId]/index.tsx
  src/components/common/button/Styled/StyledButton.tsx
  src/components/common/chip/Styled/StyledCategoryChip.tsx
  src/components/product/ProductDetail.tsx
  src/components/product/ProductDetail/ProductText/index.tsx
  src/components/product/ProductDetail/ProductText/styled.tsx
  src/components/product/ProductDetail/ShareButtons/index.tsx
  src/components/product/ProductDetail/ShareButtons/styled.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/ProductDetail/styled.tsx
  src/components/product/ProductLayout/index.tsx
  src/components/product/ProductLayout/styled.tsx
Labels: 디자인

#34 refactor: Input컴포넌트 React-hook-form 적용 사용 예시 작성
  src/components/common/input/ImageInput.tsx
  src/components/common/input/InputExamples.tsx
  src/components/common/input/NicknameInput.tsx
  src/components/common/input/ProductNameInput.tsx
  src/components/common/input/Styled/StyledInput.tsx
  src/components/common/input/TextBox.tsx
Labels: 기능

#35 Design: products페이지/21/statistics 컴포넌트 디자인 구현
  pages/products/[productId]/index.tsx
  src/components/product/StatisticsItem/index.tsx
  src/components/product/StatisticsItem/styled.tsx
  src/components/product/StatisticsList/index.tsx
  src/components/product/StatisticsList/styled.tsx
  src/utils/statisticalCalculator.tsx
Labels: 디자인

#38 Feat/30/회원가입 폼 이메일, 닉네임 Input 구현 + 에러메시지, 정규표현식 상수화
  pages/signup/index.tsx
  src/components/auth/signUp/SignUpForm.tsx
  src/components/auth/signUp/signUp
  src/constant/ERROR_MESSAGE.ts
  src/constant/REGEX.ts
Labels: 기능

#40 design: Password on off 버튼 구현
  src/components/common/input/Styled/StyledInput.tsx
Labels: 디자인

#44 feat: SignUpForm의 비밀번호, 비밀번호 확인, 가입하기 버튼 구현
  src/components/auth/signUp/SignUpForm.tsx
  src/components/common/input/Styled/StyledInput.tsx
Labels: 기능

#46 Feat/42/ranking컴포넌트
  src/apis/ranking/index.ts
  src/components/common/chip/Styled/StyledRankingChip.tsx
  src/components/common/menu/RankingListItem.tsx
  src/components/home/Ranking/Ranking.tsx
  src/components/home/Ranking/RankingList.tsx
  src/components/home/Ranking/Styled/StyledRankingList.tsx
Labels: 기능, 디자인

#54 Feat : category 컴포넌트 구현
  src/apis/category/index.ts
  src/components/home/Category/CategoryList.tsx
  src/components/home/Category/Styled/StyledCategory.tsx
  src/components/home/Category/Styled/StyledCategoryList.tsx
  src/components/home/Category/category.tsx
Labels: 기능, 디자인

#52 refactor: accessToken, userId 저장 cookie에서 localstorage 사용으로 변경
  src/components/auth/signUp/SignUpForm.tsx
  src/utils/getCookieData.ts
  src/utils/resetCookieData.ts
Labels: 기능

#53 feat: signUp페이지 로그인 상태 시 홈페이지 이동
  pages/signup/index.tsx
Labels: 기능

#58 Feat/55/main레이아웃
  pages/index.tsx
  src/components/common/card/Card.tsx
  src/components/home/Category/Styled/StyledCategoryList.tsx
  src/components/home/HomeLayout/HomeLayout.tsx
  src/components/home/HomeLayout/Styled/StyledHomeLayout.tsx
Labels: 디자인

#60 Feat: SignInForm 구현 및 SignUpForm 수정
  pages/signin/index.tsx
  src/apis/auth/index.ts
  src/apis/auth/signUp/index.ts
  src/apis/auth/signUp/schema.ts
  src/components/auth/Styled/StyledAuthForm.tsx
  src/components/auth/signIn/SignInForm.tsx
  src/components/auth/signIn/signin
  src/components/auth/signUp/SignUpForm.tsx
  src/constant/ERROR_MESSAGE.ts
  src/constant/PLACEHOLDER_MESSAGE.ts
  src/types/auth/authDataType.ts
  src/types/auth/signUp/signUpData.ts
Labels: 기능, 디자인

#63 feat: 로그인 상태, signin페이지 접근하면 /으로 이동
  pages/signin/index.tsx
Labels: 기능

#66 Design/64/간편로그인버튼디자인
  pages/signin/index.tsx
  public/icons/circle.svg
  src/components/oauth/OauthSignInBox.tsx
  src/components/oauth/Styled/StyledOauth.tsx
Labels: 디자인

#70 Design/31/Gnb 구현
  pages/_app.tsx
  src/components/gnb/11
  src/components/gnb/GnbButton.tsx
  src/components/gnb/Searchbar.tsx
  src/components/gnb/Styled/StyledButton.tsx
  src/components/gnb/Styled/StyledContainer.tsx
  src/components/gnb/Styled/StyledMenuLogo.tsx
  src/components/gnb/Styled/StyledSearchContainer.tsx
  src/components/gnb/gnb.tsx
Labels: 디자인

#69 fix: font깜빡임 현상 수정
  pages/_app.tsx
  styles/GlobalStyle.ts
  styles/font.css
  styles/globals.css
Labels: 버그

#72 feat: gnb 디자인 수정, 로고 클릭시 홈 이동, 로그인 상태 확인 구현 + 서버 오류 해결
  src/components/gnb/Searchbar.tsx
  src/components/gnb/Styled/StyledButton.tsx
  src/components/gnb/Styled/StyledContainer.tsx
  src/components/gnb/Styled/StyledMenuLogo.tsx
  src/components/gnb/Styled/StyledSearchContainer.tsx
  src/components/gnb/gnb.tsx
Labels: 버그, 기능, 디자인

#73 Feat: sortDropdown 컴포넌트 구현
  src/components/common/button/SortDropdown.tsx
  src/components/common/button/Styled/StyledSortDropdown.tsx
Labels: 기능, 디자인

#79 Fix: SortDropdown의 재활용성을 위해 정렬기준 map 수정
  src/components/common/button/SortDropdown.tsx
  src/components/product/ReviewList/index.tsx
Labels: 버그, 기능

#80 Feat: review생성 모달 api기능 구현
  next.config.mjs
  pages/products/[productId]/index.tsx
  public/icons/closeSvgr.svg
  public/icons/photoSvgr.svg
  src/apis/image/index.tsx
  src/apis/image/schema.tsx
  src/apis/review/schema.ts
  src/components/common/input/FormImageInput/index.tsx
  src/components/common/input/FormImageInput/styled.tsx
  src/components/common/input/FormTextInput/index.tsx
  src/components/common/modal/Modal.tsx
  src/components/product/ImageInput/index.tsx
  src/components/product/ModalReview/index.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/RatingStar/index.tsx
  src/components/product/ReviewItem/ReviewItemUser/index.tsx
  src/lib/axiosInstance.ts
Labels: 기능

#82 Feat/74/Oauth google 로그인 / 회원가입 구현
  pages/_app.tsx
  pages/oauth/signup/[provider].tsx
  src/apis/oauth/index.ts
  src/components/auth/oauth/OauthSignUpForm.tsx
  src/components/oauth/OauthSignInBox.tsx
  src/lib/OauthProvider.tsx
  src/routes.ts
  src/types/oauth/oauthDataType.ts
Labels: 기능

#83 Chore: README.md 초안
  README.md
Labels: 디자인

#85 feat: signIn 체크 Hook 생성 및 auth/oauth 페이지 적용
  pages/oauth/signup/[provider].tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  src/hooks/useCheckSignInAuthPage.ts
Labels: 기능

#88 Feat: Sidebar 구현
  src/components/gnb/GnbButton.tsx
  src/components/gnb/SideBar.tsx
  src/components/gnb/Styled/StyledButton.tsx
  src/components/gnb/gnb.tsx
Labels: 기능

#89 Design: userId 일치여부로 찜, 편집버튼, 리뷰 수정삭제버튼 스타일 수정
  pages/_app.tsx
  pages/products/[productId]/index.tsx
  src/components/product/ProductDetail/ProductText/styled.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/ReviewItem/ReviewFooter/index.tsx
  src/components/product/ReviewItem/index.tsx
  src/routes.ts
Labels: 디자인

#91 Feat: 상품 찜 등록/취소 이벤트, 리뷰 좋아요 취소 이벤트 Api 요청 구현
  public/icons/blurData.svg
  src/apis/product/index.ts
  src/apis/review/index.ts
  src/components/product/ProductDetail/ProductText/index.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/ProductLayout/styled.tsx
  src/components/product/ReviewItem/ReviewFooter/index.tsx
Labels: 기능

#96 feat: accessToken HttpOnly Cookie 설정을 위한 BFF 구현
  pages/api/getToken.ts
  pages/api/resetToken.ts
  pages/api/setToken.ts
  src/apis/auth/index.ts
  src/routes.ts
Labels: 기능

#97 Feat/59/search데이터페이지
  pages/search.tsx
  public/icons/filter.svg
  src/components/gnb/Searchbar.tsx
  src/components/home/Category/CategoryList.tsx
  src/components/home/Category/Styled/StyledCategory.tsx
  src/components/home/Category/Styled/StyledCategoryList.tsx
  src/components/home/Category/category.tsx
  src/components/search/CategoryDropDown/CategoryDropDown.tsx
  src/components/search/CategoryDropDown/Styled/StyledCategoryDropDown.tsx
  src/components/search/SearchCardList/SearchCardList.tsx
  src/components/search/SearchLayout/SearchLayout.tsx
  src/components/search/SearchLayout/Styled/StyledSearchLayout.tsx
  src/components/search/SearchProducts/SearchProducts.tsx
  src/components/search/SearchProducts/Styled/StyledSearchProduct.tsx
  src/components/search/SearchTitle/SearchTitle.tsx
  src/components/search/SearchTitle/Styled/StyledSearchTitle.tsx
  src/hooks/useFilterSearch.ts
Labels: 기능, 디자인

#101 feat: mypage와 user 페이지에 필요한 api 구현
  src/apis/user/index.ts
  src/types/user/userDataType.ts
Labels: 기능

#104 Feat/102/유저팔로워팔로잉모달
  next.config.mjs
  src/apis/user/index.ts
  src/components/profiles/11
  src/components/profiles/FollowInfoModal.tsx
  src/components/profiles/Styled/StyledFollowUser.tsx
  src/types/user/userDataType.ts
Labels: 기능

#99 refactor: Auth페이지 localStorage accessToken > Cookie로 변경
  src/apis/auth/index.ts
  src/components/auth/oauth/OauthSignUpForm.tsx
  src/components/auth/signIn/SignInForm.tsx
  src/components/auth/signUp/SignUpForm.tsx
  src/hooks/useCheckSignInAuthPage.ts
Labels: 기능

#103 Feat, Design : ModalEdit(상품 편집) 컴포넌트 구현
  package-lock.json
  package.json
  pages/products/[productId]/index.tsx
  public/icons/select_arrow.svg
  src/apis/product/index.ts
  src/apis/user/index.ts
  src/components/common/button/Styled/StyledSelectDropdown.tsx
  src/components/common/input/FormImageInput/index.tsx
  src/components/common/input/FormImageInput/styled.tsx
  src/components/common/input/FormMultiImageInput/index.tsx
  src/components/common/input/FormMultiImageInput/styled.tsx
  src/components/common/input/FormSelectCategory/index.tsx
  src/components/common/input/FormSelectInput/index.tsx
  src/components/common/input/FormSelectInput/styled.tsx
  src/components/common/input/FormTextInput/index.tsx
  src/components/common/input/FormTextareaInput/index.tsx
  src/components/product/ModalEdit/FormSelectProduct/index.tsx
  src/components/product/ModalEdit/index.tsx
  src/components/product/ModalEdit/styled.tsx
  src/components/product/ModalReview/index.tsx
  src/components/product/ProductDetail/index.tsx
  src/constant/ERROR_MESSAGE.ts
  src/routes.ts
  styles/GlobalStyle.ts
Labels: 기능, 디자인

#108 Design : 상품통계 평점 연결, 리뷰 없을때 스타일 추가
  pages/products/[productId]/index.tsx
  src/apis/product/schema.ts
  src/components/product/ReviewList/index.tsx
  src/components/product/ReviewList/styled.tsx
  src/utils/statisticalCalculator.tsx
Labels: 디자인

#110 refactor : search 페이지 카테고리, 검색 기능 수정
  src/components/gnb/Searchbar.tsx
  src/components/home/Category/category.tsx
  src/hooks/useFilterSearch.ts
Labels: 기능

#113 feat: 프로필 수정 모달 구현
  pages/test.tsx
  src/apis/user/index.ts
  src/components/common/input/Styled/StyledImageInput.tsx
  src/components/product/ModalReview/index.tsx
  src/components/profiles/FollowInfoModal.tsx
  src/components/profiles/ProfileEditModal.tsx
  src/components/profiles/Styled/StyledProfileEdit.tsx
  src/types/user/userDataType.ts
Labels: 기능

#115 gnb메뉴 번쩍임수정, 모바일사이즈 로고 수정
  next.config.mjs
  src/components/gnb/Logo.tsx
  src/components/gnb/Searchbar.tsx
  src/components/gnb/Styled/StyledContainer.tsx
  src/components/gnb/Styled/StyledMenuLogo.tsx
  src/components/gnb/Styled/StyledSearchContainer.tsx
  src/components/gnb/gnb.tsx
Labels: 기능

#119 Fix/114/랭킹팔로워수수정
  src/apis/user/index.ts
  src/components/home/Ranking/Ranking.tsx
Labels: 기능

#121 feat: 팔로우 버튼 / 기능 구현
  src/apis/follow/index.ts
  src/components/profiles/FollowButton.tsx
  src/components/profiles/Styled/StyledFollowButton.tsx
Labels: 기능

#123 feat:마이 페이지 프로필 편집, 로그아웃 버튼 구현
  pages/test.tsx
  src/components/profiles/MyPageProfileButtons.tsx
  src/components/profiles/Styled/StyledMyPageButton.tsx
Labels: 기능

#124 Fix : 상품조회 로직수정
  pages/products/index.tsx
  src/apis/product/index.ts
  src/components/gnb/Searchbar.tsx
  src/components/home/BaseCardList/BaseCardList.tsx
  src/components/home/Category/CategoryList.tsx
  src/components/search/SearchCardList/SearchCardList.tsx
  src/components/search/SearchProducts/SearchProducts.tsx
  src/components/search/SearchTitle/SearchTitle.tsx
  src/components/search/getCategoryName.ts
  src/hooks/useFilterSearch.ts
  src/routes.ts
Labels: 기능

#126 Feat : review 목록 무한스크롤 리펙토링
  package-lock.json
  package.json
  pages/products/[productId]/index.tsx
  src/apis/product/index.ts
  src/components/product/ReviewItem/index.tsx
  src/components/product/ReviewList/index.tsx
  src/components/product/ReviewList/styled.tsx
Labels: 기능

#130 fix : 전체상품 중에 지금 핫한 상품, 별점 높은 상품 조회 로직변경
  src/components/home/BaseCardList/BaseCardList.tsx
  src/components/home/BaseCardList/RateTop6CardList.tsx
  src/components/home/BaseCardList/ReviewTop6CardList.tsx
Labels: 기능

#131 Feat: ModalDeleteReview 구현
  pages/products/[productId]/index.tsx
  src/apis/review/index.ts
  src/components/common/button/SortDropdown.tsx
  src/components/common/modal/Modal.tsx
  src/components/product/ModalDeleteReview/index.tsx
  src/components/product/ModalDeleteReview/styled.tsx
  src/components/product/ModalReview/index.tsx
  src/components/product/ReviewItem/ReviewFooter/index.tsx
  src/components/product/ReviewItem/index.tsx
  src/components/product/ReviewList/index.tsx
  src/constant/MODAL_BUTTON.ts
Labels: 기능

#133 Fix: accessToken을 localStorage에서 cookie에서 가져오는 방식으로 수정
  src/apis/auth/index.ts
  src/components/product/ProductDetail/ProductText/index.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/ReviewItem/ReviewFooter/index.tsx
  src/lib/axiosInstance.ts
Labels: 버그, 기능

#135 feat: 프로필 유저 페이지 구현중
  next.config.mjs
  pages/mypage/index.tsx
  pages/user/[userId]/index.tsx
  src/components/profiles/MyActivity.tsx
  src/components/profiles/UserProductList.tsx
  src/components/profiles/UserProfile.tsx
  src/utils/categoryList.ts
Labels: 기능

#137 feat: mypage 페이지 로그인 아닐 시, 메인 페이지로 이동
  pages/mypage/index.tsx
  pages/user/[userId]/index.tsx
  src/hooks/useCheckSIgnin.ts
Labels: 기능

#141 feat: 카카오 간편 로그인 / 회원가입 구현
  pages/_app.tsx
  src/apis/oauth/index.ts
  src/components/auth/oauth/OauthSignUpForm.tsx
  src/components/oauth/OauthSignInBox.tsx
Labels: 기능

#143 feat: 팔로우 모달 기본이미지 설정
  src/components/profiles/Styled/StyledFollowUser.tsx
Labels: 기능, 디자인

#147 feat: 팔로우 모달 무한 스크롤 마지막 표시
  src/components/profiles/FollowInfoModal.tsx
  src/components/profiles/Styled/StyledDescription.tsx
Labels: 기능

#148 Feat/107/home페이지상품추가모달
  src/apis/product/index.ts
  src/components/common/input/FormNameInput/index.tsx
  src/components/common/input/FormNameInput/styled.tsx
  src/components/home/HomeLayout/HomeLayout.tsx
  src/components/home/HomeLayout/Styled/StyledHomeLayout.tsx
  src/components/home/ModalProductAdd/ModalProductAdd.tsx
  src/components/home/ModalProductAdd/Styled/StyledModalProductAdd.tsx.tsx
  src/components/home/ProductAddButton/ProductAddButton.tsx
  src/constant/ERROR_MESSAGE.ts
Labels: 기능

#151 Feat: 카카오톡 공유하기 구현
  pages/_app.tsx
  src/components/product/ProductDetail/ProductText/index.tsx
  src/components/product/ProductDetail/ShareButtons/index.tsx
  src/components/product/ProductDetail/ShareButtons/styled.tsx
  src/components/product/ProductDetail/index.tsx
  src/components/product/ShareKakao/index.tsx
Labels: 버그, 기능

#153 feat: 이미지 등록시 random uid 생성 후 등록
  package-lock.json
  package.json
  src/apis/image/index.tsx
  src/components/profiles/ProfileEditModal.tsx
Labels: 버그, 기능

#162 feat: 비교하기 버튼 모달 구현
  src/components/product/CompareModal/CompareModal.tsx
  src/components/product/ProductDetail/index.tsx
Labels: 기능

#163 Chore: apis 타입 지정
  src/apis/auth/index.ts
  src/apis/category/index.ts
  src/apis/category/schema.tsx
  src/apis/follow/index.ts
  src/apis/image/index.tsx
  src/apis/product/index.ts
  src/apis/product/schema.ts
  src/apis/review/index.ts
  src/apis/review/schema.ts
  src/apis/user/index.ts
  src/apis/user/schema.ts
  src/components/product/ModalEdit/FormSelectProduct/index.tsx
  src/lib/axiosInstance.ts
Labels: 기능

#164 Feature/112/compare페이지구현
  pages/compare/index.tsx
  src/components/compare/Compare.tsx
  src/components/compare/CompareInput.tsx
  src/components/compare/Loading.tsx
  src/components/compare/Styled/BodyContainer.tsx
  src/components/compare/Styled/StyledList.tsx
  src/components/compare/Styled/StyledProductInput.tsx
  src/components/compare/Styled/StyledTable.tsx
  src/components/compare/Styled/StyledTableContainer.tsx
  src/components/compare/Styled/StyledTagContainer.tsx
  src/components/gnb/SideBar.tsx
Labels: 기능

#167 Fix : 상품편집(ModalEdit)의 카테고리 버그 해결 #165 + 타입에러 해결 #166
  src/components/common/input/FormMultiImageInput/index.tsx
  src/components/common/input/FormSelectCategory/index.tsx
  src/components/product/ModalEdit/FormSelectProduct/index.tsx
  src/components/product/ModalEdit/index.tsx
  src/components/product/ProductDetail/index.tsx
Labels: 버그

#171 Fix/168/카테고리선택오류수정
  next.config.mjs
  pages/products/index.tsx
  pages/search.tsx
  src/components/home/HomeLayout/HomeLayout.tsx
  src/components/search/SearchProducts/SearchProducts.tsx
  src/hooks/useFilterSearch.ts
Labels: 버그, 기능

#173 Fix : FormSelectProduct와 FormSelectCategory의 버튼 에러 수정
  public/icons/select_arrow.svg
  src/components/common/button/Styled/StyledSelectDropdown.tsx
  src/components/common/input/FormSelectCategory/index.tsx
  src/components/product/ModalEdit/FormSelectProduct/index.tsx
Labels: 버그, 디자인

#175 Fix : FormTextarea, FormImage 등 인풋 수정 및 교체
  pages/products/[productId]/index.tsx
  src/components/common/button/Styled/StyledSelectDropdown.tsx
  src/components/common/input/FormImage/index.tsx
  src/components/common/input/FormImage/styled.tsx
  src/components/common/input/FormImageInput/styled.tsx
  src/components/common/input/FormImageMulti/index.tsx
  src/components/common/input/FormImageMulti/styled.tsx
  src/components/common/input/FormMultiImageInput/index.tsx
  src/components/common/input/FormSelect/index.tsx
  src/components/common/input/FormSelect/styled.tsx
  src/components/common/input/FormSelectInput/index.tsx
  src/components/common/input/FormSelectInput/styled.tsx
  src/components/common/input/FormTextarea/index.tsx
  src/components/common/input/FormTextareaInput/index.tsx
  src/components/common/input/FormTextareaInput/styled.tsx
  src/components/common/input/Styled/StyledTextBox.tsx
  src/components/common/toast/Toast.tsx
  src/components/home/ModalProductAdd/ModalProductAdd.tsx
  src/components/product/ModalEdit/FormSelectProduct/index.tsx
  src/components/product/ModalEdit/index.tsx
  src/components/product/ModalEdit/styled.tsx
  src/components/product/ModalEditReview/index.tsx
  src/components/product/ModalReview/index.tsx
  src/components/product/ReviewItem/ReviewFooter/index.tsx
  src/constant/ERROR_MESSAGE.ts
Labels: 버그, 디자인

#181 fix:auth 관련 problems 수정
  src/apis/apis
  src/apis/oauth/index.ts
  src/components/auth/oauth/OauthSignUpForm.tsx
  src/components/common/button/Styled/StyledSortDropdown.tsx
  src/components/common/icon/11
  src/components/common/img/11
  src/components/common/input/FormNameInput/styled.tsx
  src/components/common/table/11
  src/hooks/useCheckSIgnin.ts
  src/hooks/useCheckSignInAuthPage.ts
Labels: 버그

#178 Design: FormSelect의 x 버튼 숨기고, indicator 디자인 변경
  src/components/common/button/Styled/StyledSelectDropdown.tsx
  src/components/common/input/FormSelect/index.tsx
Labels: 디자인

#182 Chore: products페이지 리뷰목록 SSR적용
  pages/products/[productId]/index.tsx
  src/components/product/ReviewList/index.tsx
Labels: 기능

#183 Feat/154/프로필스타일구현
  src/components/common/button/Styled/StyledFloatButton.tsx
  src/components/profiles/FilterProduct/FilterProduct.tsx
  src/components/profiles/MyActivity.tsx
  src/components/profiles/MyActivity/MyActivity.tsx
  src/components/profiles/MyActivity/StyledMyActivity/StyledMyActivity.tsx
  src/components/profiles/UserProductList.tsx
  src/components/profiles/UserProfile.tsx
Labels: 디자인

#186 auth,gnb - aceessToken 저장방식 변경 및 gnb 로그인 체크 방식 변경
  src/components/auth/oauth/OauthSignUpForm.tsx
  src/components/auth/signIn/SignInForm.tsx
  src/components/auth/signUp/SignUpForm.tsx
  src/components/gnb/gnb.tsx
  src/components/oauth/OauthSignInBox.tsx
  src/components/profiles/MyPageProfileButtons.tsx
Labels: 버그

#192 Feature/112/compare페이지구현
  pages/compare/index.tsx
  src/apis/product/index.ts
  src/components/common/button/Styled/StyledButton.tsx
  src/components/compare/Compare.tsx
  src/components/compare/CompareInput.tsx
  src/components/compare/CompareResultTable.tsx
  src/components/compare/Description.tsx
  src/components/compare/Loading.tsx
  src/components/compare/Product1.tsx
  src/components/compare/Product2.tsx
  src/components/compare/Styled/BodyContainer.tsx
  src/components/compare/Styled/StyledItem.tsx
  src/components/compare/Styled/StyledTable.tsx
  src/lib/axiosInstance.ts
Labels: 기능, 도움

#189 Fix/179/type에러
  src/components/common/menu/RankingListItem.tsx
  src/components/home/BaseCardList/BaseCardList.tsx
  src/components/home/BaseCardList/RateTop6CardList.tsx
  src/components/home/BaseCardList/ReviewTop6CardList.tsx
  src/components/home/Category/CategoryList.tsx
  src/components/home/Category/Styled/StyledCategoryList.tsx
  src/components/home/ModalProductAdd/ModalProductAdd.tsx
  src/components/home/Ranking/Ranking.tsx
  src/components/search/SearchCardList/SearchCardList.tsx
  src/components/search/SearchProducts/SearchProducts.tsx
  src/components/search/SearchTitle/SearchTitle.tsx
Labels: 버그, 기능

#198 Fix/197/랭킹로직수정
  src/components/home/Ranking/Ranking.tsx
Labels: 기능

#202 fix:follow 모달 오류 수정
  src/components/profiles/FollowInfoModal.tsx
  src/components/profiles/UserProfile.tsx
Labels: 버그

#204 Design : Styled ModalEdit 입력 폰트 색변경
  src/components/common/button/Styled/StyledSelectDropdown.tsx
Labels: 디자인

#206 Fix : 상품편집모달에서 상품명 인풋 수정
  pages/products/[productId]/index.tsx
  src/components/common/input/FormProductNameInput/index.tsx
  src/components/common/input/FormProductNameInput/styled.tsx
  src/components/common/input/FormSelect/index.tsx
  src/components/product/ModalEdit/index.tsx
  src/constant/ERROR_MESSAGE.ts
Labels: 기능
